import sys

warming_comment = """
;=============================================================================================
;Warning, this file has been automatically generated. 
;DO NOT MODIFY THIS FILE DIRECTLY.
;
;Generated by build_asm.py
;=============================================================================================



"""

import_string = "#import"

def build(dir: str, main_file: str, output_filename: str):
    main_class_file_str = ""
    main_class_file = open(f"{dir}/{main_file}", "r")
    lines = main_class_file.readlines()
    import_files = []

    # Find all imports
    for line in lines:
        if line[0] is '#' and import_string in line:
            import_call = line.replace(import_string, '').strip()
            print(f'Found {import_call}')
            import_files.append(import_call)
        else:
            main_class_file_str += line

    
    main_class_file.close()

    with open(output_filename, "wb") as outfile:
        outfile.write(str.encode(warming_comment))
        outfile.write(str.encode(main_class_file_str))
        main_class_file.close()

        for file in import_files:
            with open(f"{dir}/{file}", "rb") as infile:
                outfile.write(infile.read())
    
    print(f"{output_filename} has been written!")



build(sys.argv[1], sys.argv[2], sys.argv[3])

